apiVersion: v2
name: ethgas
description: ETHGas Helm Chart
type: application
version: 0.3.7
appVersion: "0.3.7"
maintainers:
  - name: aivarasko
  - name: matilote

dependencies:
  - name: common
    repository: file://../common
    version: 1.0.0
