{{- range $projectName, $projectConfig := .Values.projects }}
{{- $ctx := dict "root" $ "projectName" $projectName }}
{{- $defaults := $.Values.defaults }}
{{- $sm := $projectConfig.serviceMonitor | default $defaults.serviceMonitor }}
{{- if $sm.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "drpc-nodecore.projectName" $ctx }}
  {{- with $sm.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "drpc-nodecore.projectLabels" $ctx | nindent 4 }}
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $sm.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ $sm.interval }}
      {{- with $sm.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: true
      port: metrics
      path: /metrics
      scheme: http
      {{- with $sm.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  jobLabel: {{ include "drpc-nodecore.projectName" $ctx }}
  selector:
    matchLabels:
      {{- include "drpc-nodecore.projectSelectorLabels" $ctx | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
