---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "drpc-nodecore.fullname" . }}
  labels:
    {{- include "drpc-nodecore.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: rpc-proxy
      port: 8080
      targetPort: rpc-proxy
      protocol: TCP
    - name: nodecore-metrics
      port: 9093
      targetPort: nodecore-metrics
      protocol: TCP
  selector:
    {{- include "drpc-nodecore.selectorLabels" . | nindent 4 }}
