---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "drpc-nodecore.fullname" . }}
  labels:
    {{- include "drpc-nodecore.labels" . | nindent 4 }}
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 8080
      targetPort: {{ if .Values.nginxSidecar.enabled }}rpc-proxy{{ else }}rpc{{ end }}
    - name: metrics
      port: 9093
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "drpc-nodecore.selectorLabels" . | nindent 4 }}
