# Override the chart name or the full release name
# The release name will be used as the service name
nameOverride: ""
fullnameOverride: ""

# The SLO Window. This determines the default burn rates and alarm windows!
# Note that an existing matching Sloth instance for this window must exist
# Check here: https://github.com/NethermindEth/argocd/tree/main/ovh/clusters/apps-prod-1/angkor-platform/sloth
# Or the equivalent location for your cluster/environment to see the available windows
window: 30d

# Configure these according to your team, they'll be used for labeling and routing alerts
labels:
  group: ""
  team: ""
  project: ""

# A map, where the key is the name of the SLO and the value is the information
# For more information on SLOs, see https://www.notion.so/nethermind/Defining-SLOs-2a1360fc38d080cda69df39ada0e6186
slos: {}
  # availability:
  #   objective: 96.0  # Objective is a number from 0 to 100
  #   description: "Availability SLO based on requests in foobar"  # A description for the SLO
  #   queries:  # Error and Total queries, as written in Prometheus Query. Replace the rate window with `{{ .window }}`
  #     error: |
  #       sum by (job) (rate(some_fancy_query{status="error"}[{{ .window }}]))
  #     total: |
  #       sum by (job) (rate(some_fancy_query[{{ .window }}]))
  #   alerting:
  #     enabled: true  # Enabled here is optional and true by default
  #     # No need to add severity or team, project and group labels, those are added automatically
  #     # Extra labels are optional and can be omitted
  #     extraLabels:
  #       category: "availability"
  #     summary: "Error rate for APPLICATION is too high"  # A summary or title for the alert, passed literally to Prometehus
  #     # A full description of the alert, passed literally to Prometehus
  #     description: >
  #       The current error ratio for APPLICATION {{ $labels.job }} requests is high enough to exhaust the error budget quickly!
  #       Current error rate rate: {{ $value | printf "%.3f" }}
  #     runbook: "https://example.com"  # All good alerts have a runbook to help on-call
