{{- if .Values.HTTPRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.HTTPRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- range $ref := .Values.HTTPRoute.parentRefs }}
  - group: {{ $ref.group | default "gateway.networking.k8s.io" }}
    kind: {{ $ref.kind | default "Gateway" }}
    name: {{ $ref.name }}
    namespace: {{ $ref.namespace }}
  {{- end }}
  hostnames:
  {{- range $hostname := .Values.HTTPRoute.hostnames }}
  - {{ $hostname | quote }}
  {{- end }}
  rules:
  {{- range $rule := .Values.HTTPRoute.rules }}
  - backendRefs:
    {{- range $ref := $rule.backendRefs }}
    - group: {{ $ref.group | default "" | quote }}
      kind: {{ $ref.kind | default "Service" }}
      name: {{ include "common.names.fullname" $ }}
      port: {{ $ref.port }}
      weight: {{ $ref.weight | default 1 }}
    {{- end }}
    {{- with $rule.matches }}
    matches:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $rule.filters }}
    filters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
