apiVersion: v2
name: execution-beacon
description: A Helm chart for deploying Ethereum execution and consensus clients
type: application
version: 1.0.30
keywords:
  - ethereum
  - blockchain
  - nethermind
  - prysm
  - reth
  - lighthouse
  - nimbus
  - lodestar
  - erigon
  - teku
  - besu
  - p2p
  - taiko

home: https://www.ethereum.org/

maintainers:
  - name: 0xDones
  - name: matilote
  - name: aivarasko

dependencies:
  - name: common
    repository: file://../common
    version: 1.0.0
