{{- if .Values.centralMonitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release.name" . }}-prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 12s
      evaluation_interval: 12s
    remote_write:
      - url: {{ $.Values.centralMonitoring.promEndpoint }}
        authorization:
          credentials_file: /etc/prometheus/secrets/token
    scrape_configs:
      - job_name: '{{ include "release.name" . }}'
        static_configs:
          - targets: ['{{ include "release.name" . }}:3620']
        {{- with .Values.centralMonitoring.scrapeConfig.relabelConfigs }}
        relabel_configs:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
